# Docker Compose for Phala Cloud deployment with separate frontend
# This is for frontend-only deployment that connects to a separate backend
# The image parmenidesxyz/kurtosis-frontend:phala has the backend URL baked in

services:
  kurtosis-frontend:
    image: parmenidesxyz/kurtosis-frontend:phala
    container_name: kurtosis-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped